#!/bin/bash
# VC/Market Research Memo Formatter
# Specialized format for VC and market research

set -euo pipefail

RESEARCH_FILE="$1"

if [ ! -f "$RESEARCH_FILE" ]; then
    echo "Error: Research file not found: $RESEARCH_FILE"
    exit 1
fi

cat <<EOF
# Market Research Memo

**Date**: $(date "+%Y-%m-%d")
**Subject**: $(jq -r '.market_name // .original_question' "$RESEARCH_FILE")

---

## Executive Summary

$(jq -r '.summary' "$RESEARCH_FILE")

---

## Market Opportunity

### Market Size & Growth

| Metric | Value | Year | Methodology | Confidence |
|--------|-------|------|-------------|------------|
$(jq -r '.tam? | "| TAM | \(.value) | \(.year) | \(.methodology) | \(.confidence // "medium") |"' "$RESEARCH_FILE")
$(jq -r '.sam? | "| SAM | \(.value) | \(.year) | Bottom-up | medium |"' "$RESEARCH_FILE")
$(jq -r '.som? | "| SOM (\(.timeframe)) | \(.value) | Projection | \(.confidence // "medium") |"' "$RESEARCH_FILE")

**Growth Metrics**:
$(jq -r '.growth_metrics? | "- CAGR (5yr): \(.cagr_5yr)\n- YoY Growth: \(.yoy_growth)\n- 2030 Forecast: \(.forecast_2030)"' "$RESEARCH_FILE")

### Market Segments

$(jq -r '.market_segments[]? | "#### \(.name)\n- Size: \(.size)\n- Growth Rate: \(.growth_rate)\n- Characteristics: \(.characteristics)\n"' "$RESEARCH_FILE")

### Market Maturity & Adoption

- **Stage**: $(jq -r '.market_maturity // "N/A"' "$RESEARCH_FILE")
- **Adoption**: $(jq -r '.adoption_curve.stage // "N/A"' "$RESEARCH_FILE")
- **Penetration Rate**: $(jq -r '.adoption_curve.penetration_rate // "N/A"' "$RESEARCH_FILE")

---

## Competitive Landscape

### Key Players

| Company | Stage | Funding | Valuation | Positioning |
|---------|-------|---------|-----------|-------------|
$(jq -r '.competitors[]? | "| \(.name) | \(.stage) | \(.funding_total) | \(.last_valuation // "N/A") | \(.target_market) |"' "$RESEARCH_FILE")

### Market Structure

- **Leaders**: $(jq -r '.market_structure.leaders | join(", ")' "$RESEARCH_FILE" 2>/dev/null || echo "N/A")
- **Challengers**: $(jq -r '.market_structure.challengers | join(", ")' "$RESEARCH_FILE" 2>/dev/null || echo "N/A")
- **Concentration**: $(jq -r '.market_structure.market_concentration // "N/A"' "$RESEARCH_FILE")

### Recent M&A Activity

$(jq -r '.ma_activity[]? | "- **\(.date)**: \(.acquirer) acquired \(.target) for \(.value)\n  - Rationale: \(.rationale)\n"' "$RESEARCH_FILE" || echo "No recent M&A activity noted.")

---

## Financial Analysis

$(jq -r '.financial_data[]? | "### \(.company)\n\n**Revenue Metrics**:\n- Revenue: \(.revenue_metrics.revenue)\n- ARR: \(.revenue_metrics.arr)\n- Growth (YoY): \(.revenue_metrics.growth_rate_yoy)\n\n**Unit Economics**:\n- CAC: \(.unit_economics.cac)\n- LTV: \(.unit_economics.ltv)\n- LTV:CAC: \(.unit_economics.ltv_cac_ratio)\n- Payback: \(.unit_economics.payback_period_months) months\n- Gross Margin: \(.unit_economics.gross_margin)\n\n**SaaS Metrics**:\n- NRR: \(.saas_metrics.nrr)\n- Churn: \(.saas_metrics.churn_rate)\n\n"' "$RESEARCH_FILE")

---

## Investment Considerations

### Market Drivers
$(jq -r '.market_drivers[]? | "- \(.)"' "$RESEARCH_FILE")

### Key Risks
$(jq -r '.market_challenges[]? | "- \(.)"' "$RESEARCH_FILE")

### Bull Case
$(jq -r '.investment_thesis.bull_case[]? | "- \(.)"' "$RESEARCH_FILE" || echo "TBD based on findings")

### Bear Case
$(jq -r '.investment_thesis.bear_case[]? | "- \(.)"' "$RESEARCH_FILE" || echo "TBD based on findings")

---

## Data Quality & Sources

**Primary Sources**:
$(jq -r '[.sections[]?.citations[]?] | unique_by(.url) | .[] | select(.credibility == "official" or .credibility == "high") | "- [\(.title)](\(.url))"' "$RESEARCH_FILE")

**Data Quality Notes**:
$(jq -r '.data_quality_notes[]? | "- \(.)"' "$RESEARCH_FILE" || echo "- Market sizing based on public market reports\n- Funding data from Crunchbase and press releases\n- Financial estimates where disclosed data unavailable")

---

## Validation & Confidence

$(jq -r '.validation.quality_assessment | "- **Source Diversity**: \(.source_diversity)\n- **Data Recency**: \(.recency)\n- **Overall Confidence**: \(.overall_confidence // "medium")"' "$RESEARCH_FILE")

$(if jq -e '.validation.concerns | length > 0' "$RESEARCH_FILE" >/dev/null 2>&1; then
    echo -e "\n### Data Concerns\n"
    jq -r '.validation.concerns[] | "- \(.description)"' "$RESEARCH_FILE"
fi)

---

*Generated by Deep CConductor - VC/Market Mode*
*Powered by [Claude Code](https://claude.com/claude-code)*
EOF
