name: CI

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  lint:
    name: Lint Shell Scripts
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install lint dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y jq ripgrep
      
      - name: Install ShellCheck
        run: |
          # Install latest stable shellcheck from official source
          wget -qO- "https://github.com/koalaman/shellcheck/releases/download/stable/shellcheck-stable.linux.x86_64.tar.xz" | tar -xJv
          sudo cp "shellcheck-stable/shellcheck" /usr/bin/
          shellcheck --version
      
      - name: Run ShellCheck
        run: |
          echo "Linting shell scripts..."
          # Note: No severity filtering - checks style, info, warning, and error levels
          # This ensures highest code quality standards
          find . -name "*.sh" -type f -not -path "./.history/*" -not -path "./.git/*" | while read -r file; do
            echo "Checking: $file"
            shellcheck "$file" || exit 1
          done
          echo "✓ All scripts passed ShellCheck"

      - name: Run jq lint
        run: |
          bash scripts/lint-jq-patterns.sh
          bash scripts/audit-jq-usage.sh /tmp/jq-audit-ci.json

      - name: Check bash runtime usage
        run: |
          bash scripts/lint-bash-runtime.sh

  test-scripts:
    name: Test Scripts
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Install dependencies
        run: |
          if [[ "$OSTYPE" == "darwin"* ]]; then
            brew install jq curl bash bc python3
          else
            sudo apt-get update
            sudo apt-get install -y jq curl bash bc python3
          fi
      
      - name: Test platform-paths.sh
        run: |
          chmod +x src/utils/platform-paths.sh
          ./src/utils/platform-paths.sh --show
          echo "✓ Platform paths detected"
      
      - name: Test version manager syntax
        run: |
          chmod +x src/utils/version-manager.sh
          bash -n src/utils/version-manager.sh
          echo "✓ Version manager syntax valid"
      
      - name: Test cconductor script syntax
        run: |
          chmod +x cconductor
          bash -n cconductor
          echo "✓ CConductor script syntax valid"
      
      - name: Test install script syntax
        run: |
          chmod +x install.sh
          bash -n install.sh
          echo "✓ Install script syntax valid"

  verify-permissions:
    name: Verify File Permissions
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Check executable permissions
        run: |
          echo "Checking executable permissions..."
          
          files_to_check=(
            "cconductor"
            "install.sh"
            "src/init.sh"
            "src/utils/platform-paths.sh"
            "src/utils/version-manager.sh"
          )
          
          for file in "${files_to_check[@]}"; do
            if [ -f "$file" ]; then
              if [ -x "$file" ]; then
                echo "✓ $file is executable"
              else
                echo "✗ $file is NOT executable"
                exit 1
              fi
            fi
          done
